modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="regions_unexplored"
version="0.5.4"
displayName="Regions Unexplored"
displayURL="https://discord.gg/Ss8UHPqHPj"
logoFile="ruthumb.png"
credits="Terrablender:Adubbz"
authors="UHQ_GAMES"
description='''
Regions Unexplored is a mod that aims to add new content to the overworld. Currently adds over 70 new biomes!
'''

[[dependencies.regions_unexplored]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.regions_unexplored]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.regions_unexplored]]
modId="terrablender"
mandatory=true
versionRange="[2.0.1.128,)"
ordering="NONE"
side="BOTH"